/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppHelpRouteImport } from './routes/_app/help'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects.$projectId'
import { Route as ApiV1ProjectsRouteImport } from './routes/api/v1/projects'
import { Route as ApiV1ProjectsProjectIdRouteImport } from './routes/api/v1/projects.$projectId'
import { Route as ApiV1ProjectsProjectIdStatusesRouteImport } from './routes/api/v1/projects.$projectId.statuses'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const ApiV1ProjectsRoute = ApiV1ProjectsRouteImport.update({
  id: '/api/v1/projects',
  path: '/api/v1/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProjectsProjectIdRoute = ApiV1ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ApiV1ProjectsRoute,
} as any)
const ApiV1ProjectsProjectIdStatusesRoute =
  ApiV1ProjectsProjectIdStatusesRouteImport.update({
    id: '/statuses',
    path: '/statuses',
    getParentRoute: () => ApiV1ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/help': typeof AppHelpRoute
  '/settings': typeof AppSettingsRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/api/v1/projects': typeof ApiV1ProjectsRouteWithChildren
  '/api/v1/projects/$projectId': typeof ApiV1ProjectsProjectIdRouteWithChildren
  '/api/v1/projects/$projectId/statuses': typeof ApiV1ProjectsProjectIdStatusesRoute
}
export interface FileRoutesByTo {
  '/help': typeof AppHelpRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/api/v1/projects': typeof ApiV1ProjectsRouteWithChildren
  '/api/v1/projects/$projectId': typeof ApiV1ProjectsProjectIdRouteWithChildren
  '/api/v1/projects/$projectId/statuses': typeof ApiV1ProjectsProjectIdStatusesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/help': typeof AppHelpRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/api/v1/projects': typeof ApiV1ProjectsRouteWithChildren
  '/api/v1/projects/$projectId': typeof ApiV1ProjectsProjectIdRouteWithChildren
  '/api/v1/projects/$projectId/statuses': typeof ApiV1ProjectsProjectIdStatusesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/settings'
    | '/projects/$projectId'
    | '/api/v1/projects'
    | '/api/v1/projects/$projectId'
    | '/api/v1/projects/$projectId/statuses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/help'
    | '/settings'
    | '/'
    | '/projects/$projectId'
    | '/api/v1/projects'
    | '/api/v1/projects/$projectId'
    | '/api/v1/projects/$projectId/statuses'
  id:
    | '__root__'
    | '/_app'
    | '/_app/help'
    | '/_app/settings'
    | '/_app/'
    | '/_app/projects/$projectId'
    | '/api/v1/projects'
    | '/api/v1/projects/$projectId'
    | '/api/v1/projects/$projectId/statuses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiV1ProjectsRoute: typeof ApiV1ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/v1/projects': {
      id: '/api/v1/projects'
      path: '/api/v1/projects'
      fullPath: '/api/v1/projects'
      preLoaderRoute: typeof ApiV1ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects/$projectId': {
      id: '/api/v1/projects/$projectId'
      path: '/$projectId'
      fullPath: '/api/v1/projects/$projectId'
      preLoaderRoute: typeof ApiV1ProjectsProjectIdRouteImport
      parentRoute: typeof ApiV1ProjectsRoute
    }
    '/api/v1/projects/$projectId/statuses': {
      id: '/api/v1/projects/$projectId/statuses'
      path: '/statuses'
      fullPath: '/api/v1/projects/$projectId/statuses'
      preLoaderRoute: typeof ApiV1ProjectsProjectIdStatusesRouteImport
      parentRoute: typeof ApiV1ProjectsProjectIdRoute
    }
  }
}

interface AppRouteChildren {
  AppHelpRoute: typeof AppHelpRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHelpRoute: AppHelpRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiV1ProjectsProjectIdRouteChildren {
  ApiV1ProjectsProjectIdStatusesRoute: typeof ApiV1ProjectsProjectIdStatusesRoute
}

const ApiV1ProjectsProjectIdRouteChildren: ApiV1ProjectsProjectIdRouteChildren =
  {
    ApiV1ProjectsProjectIdStatusesRoute: ApiV1ProjectsProjectIdStatusesRoute,
  }

const ApiV1ProjectsProjectIdRouteWithChildren =
  ApiV1ProjectsProjectIdRoute._addFileChildren(
    ApiV1ProjectsProjectIdRouteChildren,
  )

interface ApiV1ProjectsRouteChildren {
  ApiV1ProjectsProjectIdRoute: typeof ApiV1ProjectsProjectIdRouteWithChildren
}

const ApiV1ProjectsRouteChildren: ApiV1ProjectsRouteChildren = {
  ApiV1ProjectsProjectIdRoute: ApiV1ProjectsProjectIdRouteWithChildren,
}

const ApiV1ProjectsRouteWithChildren = ApiV1ProjectsRoute._addFileChildren(
  ApiV1ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiV1ProjectsRoute: ApiV1ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
