/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppHelpRouteImport } from './routes/_app/help'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects.$projectId'
import { Route as AppTasksTaskIdRouteImport } from './routes/_app/tasks.$taskId'
import { Route as ApiV1ProjectsRouteImport } from './routes/api/v1/projects'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app/projects.$projectId.index'
import { Route as AppProjectsProjectIdBoardRouteImport } from './routes/_app/projects.$projectId.board'
import { Route as ApiV1ProjectsProjectIdRouteImport } from './routes/api/v1/projects.$projectId'
import { Route as ApiV1TasksTaskIdRouteImport } from './routes/api/v1/tasks.$taskId'
import { Route as ApiV1ProjectsProjectIdStatusesRouteImport } from './routes/api/v1/projects.$projectId.statuses'
import { Route as ApiV1ProjectsProjectIdTasksRouteImport } from './routes/api/v1/projects.$projectId.tasks'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AppRoute,
} as any)
const ApiV1ProjectsRoute = ApiV1ProjectsRouteImport.update({
  id: '/api/v1/projects',
  path: '/api/v1/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdBoardRoute =
  AppProjectsProjectIdBoardRouteImport.update({
    id: '/board',
    path: '/board',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const ApiV1ProjectsProjectIdRoute = ApiV1ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ApiV1ProjectsRoute,
} as any)
const ApiV1TasksTaskIdRoute = ApiV1TasksTaskIdRouteImport.update({
  id: '/api/v1/tasks/$taskId',
  path: '/api/v1/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProjectsProjectIdStatusesRoute =
  ApiV1ProjectsProjectIdStatusesRouteImport.update({
    id: '/statuses',
    path: '/statuses',
    getParentRoute: () => ApiV1ProjectsProjectIdRoute,
  } as any)
const ApiV1ProjectsProjectIdTasksRoute =
  ApiV1ProjectsProjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => ApiV1ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/help': typeof AppHelpRoute
  '/settings': typeof AppSettingsRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/api/v1/projects': typeof ApiV1ProjectsRouteWithChildren
  '/projects/$projectId/board': typeof AppProjectsProjectIdBoardRoute
  '/api/v1/projects/$projectId': typeof ApiV1ProjectsProjectIdRouteWithChildren
  '/api/v1/tasks/$taskId': typeof ApiV1TasksTaskIdRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/api/v1/projects/$projectId/statuses': typeof ApiV1ProjectsProjectIdStatusesRoute
  '/api/v1/projects/$projectId/tasks': typeof ApiV1ProjectsProjectIdTasksRoute
}
export interface FileRoutesByTo {
  '/help': typeof AppHelpRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/api/v1/projects': typeof ApiV1ProjectsRouteWithChildren
  '/projects/$projectId/board': typeof AppProjectsProjectIdBoardRoute
  '/api/v1/projects/$projectId': typeof ApiV1ProjectsProjectIdRouteWithChildren
  '/api/v1/tasks/$taskId': typeof ApiV1TasksTaskIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/api/v1/projects/$projectId/statuses': typeof ApiV1ProjectsProjectIdStatusesRoute
  '/api/v1/projects/$projectId/tasks': typeof ApiV1ProjectsProjectIdTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/help': typeof AppHelpRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/api/v1/projects': typeof ApiV1ProjectsRouteWithChildren
  '/_app/projects/$projectId/board': typeof AppProjectsProjectIdBoardRoute
  '/api/v1/projects/$projectId': typeof ApiV1ProjectsProjectIdRouteWithChildren
  '/api/v1/tasks/$taskId': typeof ApiV1TasksTaskIdRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/api/v1/projects/$projectId/statuses': typeof ApiV1ProjectsProjectIdStatusesRoute
  '/api/v1/projects/$projectId/tasks': typeof ApiV1ProjectsProjectIdTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/settings'
    | '/projects/$projectId'
    | '/tasks/$taskId'
    | '/api/v1/projects'
    | '/projects/$projectId/board'
    | '/api/v1/projects/$projectId'
    | '/api/v1/tasks/$taskId'
    | '/projects/$projectId/'
    | '/api/v1/projects/$projectId/statuses'
    | '/api/v1/projects/$projectId/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/help'
    | '/settings'
    | '/'
    | '/tasks/$taskId'
    | '/api/v1/projects'
    | '/projects/$projectId/board'
    | '/api/v1/projects/$projectId'
    | '/api/v1/tasks/$taskId'
    | '/projects/$projectId'
    | '/api/v1/projects/$projectId/statuses'
    | '/api/v1/projects/$projectId/tasks'
  id:
    | '__root__'
    | '/_app'
    | '/_app/help'
    | '/_app/settings'
    | '/_app/'
    | '/_app/projects/$projectId'
    | '/_app/tasks/$taskId'
    | '/api/v1/projects'
    | '/_app/projects/$projectId/board'
    | '/api/v1/projects/$projectId'
    | '/api/v1/tasks/$taskId'
    | '/_app/projects/$projectId/'
    | '/api/v1/projects/$projectId/statuses'
    | '/api/v1/projects/$projectId/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiV1ProjectsRoute: typeof ApiV1ProjectsRouteWithChildren
  ApiV1TasksTaskIdRoute: typeof ApiV1TasksTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/v1/projects': {
      id: '/api/v1/projects'
      path: '/api/v1/projects'
      fullPath: '/api/v1/projects'
      preLoaderRoute: typeof ApiV1ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/board': {
      id: '/_app/projects/$projectId/board'
      path: '/board'
      fullPath: '/projects/$projectId/board'
      preLoaderRoute: typeof AppProjectsProjectIdBoardRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/api/v1/projects/$projectId': {
      id: '/api/v1/projects/$projectId'
      path: '/$projectId'
      fullPath: '/api/v1/projects/$projectId'
      preLoaderRoute: typeof ApiV1ProjectsProjectIdRouteImport
      parentRoute: typeof ApiV1ProjectsRoute
    }
    '/api/v1/tasks/$taskId': {
      id: '/api/v1/tasks/$taskId'
      path: '/api/v1/tasks/$taskId'
      fullPath: '/api/v1/tasks/$taskId'
      preLoaderRoute: typeof ApiV1TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects/$projectId/statuses': {
      id: '/api/v1/projects/$projectId/statuses'
      path: '/statuses'
      fullPath: '/api/v1/projects/$projectId/statuses'
      preLoaderRoute: typeof ApiV1ProjectsProjectIdStatusesRouteImport
      parentRoute: typeof ApiV1ProjectsProjectIdRoute
    }
    '/api/v1/projects/$projectId/tasks': {
      id: '/api/v1/projects/$projectId/tasks'
      path: '/tasks'
      fullPath: '/api/v1/projects/$projectId/tasks'
      preLoaderRoute: typeof ApiV1ProjectsProjectIdTasksRouteImport
      parentRoute: typeof ApiV1ProjectsProjectIdRoute
    }
  }
}

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdBoardRoute: typeof AppProjectsProjectIdBoardRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdBoardRoute: AppProjectsProjectIdBoardRoute,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppRouteChildren {
  AppHelpRoute: typeof AppHelpRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHelpRoute: AppHelpRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiV1ProjectsProjectIdRouteChildren {
  ApiV1ProjectsProjectIdStatusesRoute: typeof ApiV1ProjectsProjectIdStatusesRoute
  ApiV1ProjectsProjectIdTasksRoute: typeof ApiV1ProjectsProjectIdTasksRoute
}

const ApiV1ProjectsProjectIdRouteChildren: ApiV1ProjectsProjectIdRouteChildren =
  {
    ApiV1ProjectsProjectIdStatusesRoute: ApiV1ProjectsProjectIdStatusesRoute,
    ApiV1ProjectsProjectIdTasksRoute: ApiV1ProjectsProjectIdTasksRoute,
  }

const ApiV1ProjectsProjectIdRouteWithChildren =
  ApiV1ProjectsProjectIdRoute._addFileChildren(
    ApiV1ProjectsProjectIdRouteChildren,
  )

interface ApiV1ProjectsRouteChildren {
  ApiV1ProjectsProjectIdRoute: typeof ApiV1ProjectsProjectIdRouteWithChildren
}

const ApiV1ProjectsRouteChildren: ApiV1ProjectsRouteChildren = {
  ApiV1ProjectsProjectIdRoute: ApiV1ProjectsProjectIdRouteWithChildren,
}

const ApiV1ProjectsRouteWithChildren = ApiV1ProjectsRoute._addFileChildren(
  ApiV1ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiV1ProjectsRoute: ApiV1ProjectsRouteWithChildren,
  ApiV1TasksTaskIdRoute: ApiV1TasksTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
